server:
  port: 5080
  forward-headers-strategy: framework

spring:
  profiles:
    default: dev   # 아무것도 지정하지 않으면 자동으로 dev

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          cognito:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile

---
spring:
  config:
    import: "aws-parameterstore:/tech-gather/dev/cognito/"
  config.activate.on-profile: dev

---
spring:
  config:
    import: "aws-parameterstore:/tech-gather/prod/cognito/"
  config.activate.on-profile: prod

