spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: local-client
            client-secret: local-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            domain-uri: http://localhost/dummy-domain

        provider:
          cognito:
            authorization-uri: http://localhost/oauth2/authorize
            token-uri: http://localhost/oauth2/token
            jwk-set-uri: http://localhost/dummy/jwks.json
