plugins {
	id 'java'
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.dependency.management)
	alias(libs.plugins.kotlin.jvm) apply false
	alias(libs.plugins.kotlin.spring) apply false
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

allprojects {

	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17

	tasks.named('test') {
		useJUnitPlatform()
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		implementation libs.spring.boot.starter
		testImplementation libs.spring.boot.starter.test
		testRuntimeOnly libs.junit.platform.launcher
	}

	pluginManager.withPlugin('org.jetbrains.kotlin.jvm') {
		kotlin {
			jvmToolchain(17)
		}
	}
}

bootJar {
	enabled = false
}

jar {
	enabled = false
}