dependencies {
    implementation libs.spring.kafka
    implementation libs.bundles.spring.batch
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.data.jpa
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.batch.test
    testImplementation libs.spring.kafka.test

    implementation libs.jackson.databind

    implementation libs.slf4j.api

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    runtimeOnly libs.mysql.connector.j

    implementation("io.awspring.cloud:spring-cloud-aws-starter-parameter-store:3.4.2")
    implementation("software.amazon.awssdk:secretsmanager:2.40.16")

    implementation project(':domain')
    implementation project(':application')
}