bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation libs.spring.boot.starter.data.jpa

    implementation libs.jackson.databind
    implementation libs.jackson.datatype.jsr310

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation project(':application')

    implementation libs.querydsl.jpa, {
        artifact {
            classifier = 'jakarta'
        }
    }
    annotationProcessor libs.querydsl.apt, {
        artifact {
            classifier = 'jakarta'
        }
    }
    annotationProcessor libs.jakarta.annotation.api
    annotationProcessor libs.jakarta.persistence.api
}

def querydslDir = "$buildDir/generated/querydsl"

sourceSets {
    main.java.srcDir querydslDir
}
