server:
  port: 7500

spring:
  profiles:
    active: local

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: batch-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      topic: post
      poll-timeout: 5000
      max-empty-polls: 3

  batch:
    chunk:
      size: 100
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/techgather
    username: techgather
    password: techgather
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: false
        batch_versioned_data: true
        generate_statistics: false

---

spring:
  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: batch-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      topic: post
      poll-timeout: 5000
      max-empty-polls: 3

  batch:
    chunk:
      size: 100
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/techgather
    username: techgather
    password: techgather
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: false
        batch_versioned_data: true
        generate_statistics: false

---

spring:
  profiles:
    active: prod

  kafka:
    bootstrap-servers: localhost:9092 # GCP 인스턴스에 collector 모듈 배포 시 수정되어야 합니다.
    consumer:
      group-id: batch-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      topic: post
      poll-timeout: 5000
      max-empty-polls: 3

  batch:
    chunk:
      size: 100
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: false
        batch_versioned_data: true
        generate_statistics: false

aws:
  secret-name: prod/db/parameter